# Generated by Django 5.0.6 on 2026-08-26 22:04

import apps.campaigns.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attachments', '0001_initial'),
        ('mailboxes', '0004_mailbox_extra_folders_mailbox_folder_cursors_and_more'),
        ('workspaces', '0002_userprofile_onboarding_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignSender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('kind', models.CharField(choices=[('mailbox', 'Workspace mailbox'), ('smtp', 'External SMTP relay'), ('ses', 'Amazon SES (SMTP)'), ('sendgrid', 'SendGrid (API)'), ('mailgun', 'Mailgun (API)'), ('postmark', 'Postmark (API)')], default='mailbox', max_length=12)),
                ('from_email', models.EmailField(blank=True, default='', max_length=320)),
                ('from_name', models.CharField(blank=True, default='', max_length=160)),
                ('reply_to', models.EmailField(blank=True, default='', max_length=320)),
                ('smtp_host', models.CharField(blank=True, default='', max_length=200)),
                ('smtp_port', models.PositiveIntegerField(default=587)),
                ('smtp_use_tls', models.BooleanField(default=True)),
                ('username', models.CharField(blank=True, default='', max_length=320)),
                ('secret_encrypted', models.TextField(blank=True, default='')),
                ('region', models.CharField(blank=True, default='', help_text='SES region, e.g. eu-west-1', max_length=64)),
                ('domain', models.CharField(blank=True, default='', help_text='Mailgun sending domain', max_length=255)),
                ('daily_limit', models.PositiveIntegerField(default=0, help_text='Max sends per day. 0 = unlimited.')),
                ('hourly_limit', models.PositiveIntegerField(default=0, help_text='Max sends per hour. 0 = unlimited.')),
                ('weight', models.PositiveIntegerField(default=1)),
                ('is_overflow', models.BooleanField(default=False, help_text='Only used once the non-overflow routes have hit their caps.')),
                ('use_proxy', models.BooleanField(default=False, help_text='Route SMTP through the workspace proxy pool.')),
                ('is_active', models.BooleanField(default=True)),
                ('sent_today', models.PositiveIntegerField(default=0)),
                ('sent_this_hour', models.PositiveIntegerField(default=0)),
                ('day_started', models.DateField(blank=True, null=True)),
                ('hour_started', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mailbox', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaign_senders', to='mailboxes.mailbox')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_senders', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['is_overflow', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=998)),
                ('body', models.TextField(blank=True, default='')),
                ('is_html', models.BooleanField(default=True)),
                ('preheader', models.CharField(blank=True, default='', help_text='Preview text shown after the subject in most inboxes.', max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sending', 'Sending'), ('paused', 'Paused'), ('sent', 'Sent'), ('failed', 'Failed')], db_index=True, default='draft', max_length=12)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('per_tick_limit', models.PositiveIntegerField(default=25, help_text='Most emails to send per engine tick, across all routes.')),
                ('track_opens', models.BooleanField(default=True)),
                ('track_clicks', models.BooleanField(default=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attachments', models.ManyToManyField(blank=True, related_name='campaigns', to='attachments.attachment')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='workspaces.workspace')),
                ('senders', models.ManyToManyField(blank=True, related_name='campaigns', to='campaigns.campaignsender')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=320)),
                ('first_name', models.CharField(blank=True, default='', max_length=120)),
                ('last_name', models.CharField(blank=True, default='', max_length=120)),
                ('company', models.CharField(blank=True, default='', max_length=200)),
                ('fields', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('subscribed', 'Subscribed'), ('unsubscribed', 'Unsubscribed'), ('bounced', 'Bounced'), ('complained', 'Complained')], default='subscribed', max_length=14)),
                ('status_reason', models.CharField(blank=True, default='', max_length=255)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
                ('unsubscribe_token', models.CharField(db_index=True, default=apps.campaigns.models._token, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['email'],
            },
        ),
        migrations.CreateModel(
            name='CampaignRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('opened', 'Opened'), ('clicked', 'Clicked'), ('bounced', 'Bounced'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, default='pending', max_length=10)),
                ('token', models.CharField(db_index=True, default=apps.campaigns.models._token, max_length=64, unique=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('open_count', models.PositiveIntegerField(default=0)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('click_count', models.PositiveIntegerField(default=0)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='campaigns.campaign')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipients', to='campaigns.campaignsender')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_recipients', to='campaigns.contact')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ContactList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contacts', models.ManyToManyField(blank=True, related_name='lists', to='campaigns.contact')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_lists', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='campaign',
            name='lists',
            field=models.ManyToManyField(blank=True, related_name='campaigns', to='campaigns.contactlist'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['workspace', 'status'], name='campaigns_c_workspa_922528_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together={('workspace', 'email')},
        ),
        migrations.AddIndex(
            model_name='campaignrecipient',
            index=models.Index(fields=['campaign', 'status'], name='campaigns_c_campaig_1a8cf7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='campaignrecipient',
            unique_together={('campaign', 'contact')},
        ),
    ]
