# Generated by Django 5.0.6 on 2026-08-26 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignsender',
            name='use_for_replies',
            field=models.BooleanField(default=False, help_text='Also use this route for auto-replies once a mailbox hits its daily cap.'),
        ),
    ]
