# Generated by Django 5.0.6 on 2026-08-26 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_campaignsender_use_for_replies'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignsender',
            name='authorized_domains',
            field=models.CharField(blank=True, default='', help_text="Comma-separated domains this provider may send as. Blank = the From address's domain.", max_length=500),
        ),
    ]
