# Generated by Django 5.0.6 on 2026-08-26 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_campaignsender_reply_identity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignsender',
            name='reply_identity',
            field=models.CharField(choices=[('mailbox', "Keep the mailbox's own address"), ('route', 'Send as this route, Reply-To the mailbox')], default='route', help_text='Whose address a borrowed auto-reply is sent under.', max_length=10),
        ),
    ]
