# Generated by Django 5.0.6 on 2026-10-04 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0002_userprofile_onboarding_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProtectedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(help_text='Public URL /g/<slug>/', max_length=80, unique=True)),
                ('kind', models.CharField(choices=[('page', 'Inline page'), ('file', 'File download')], default='page', max_length=8)),
                ('ciphertext', models.BinaryField(blank=True)),
                ('content_type', models.CharField(blank=True, default='', max_length=120)),
                ('size', models.PositiveBigIntegerField(default=0, help_text='Plaintext size in bytes')),
                ('passcode_hash', models.CharField(blank=True, default='', max_length=256)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('max_views', models.PositiveIntegerField(blank=True, help_text='Blank = unlimited', null=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('allowed_referrers', models.CharField(blank=True, default='', help_text='Comma-separated; blank = no check', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('disable_right_click', models.BooleanField(default=False)),
                ('disable_copy', models.BooleanField(default=False)),
                ('disable_print', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protected_documents', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProtectedAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('referrer', models.CharField(blank=True, default='', max_length=500)),
                ('outcome', models.CharField(choices=[('granted', 'Granted'), ('denied_passcode', 'Denied — passcode'), ('expired', 'Expired'), ('over_limit', 'Over view limit'), ('denied_referrer', 'Denied — referrer'), ('inactive', 'Inactive')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='protected_content.protecteddocument')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
