# Generated by Django 5.0.6 on 2026-10-04 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protected_content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProtectedAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ciphertext', models.BinaryField(blank=True)),
                ('content_type', models.CharField(blank=True, default='', max_length=120)),
                ('size', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='protected_content.protecteddocument')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
