# Generated by Django 5.0.6 on 2026-10-04 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protected_content', '0002_protectedasset'),
    ]

    operations = [
        migrations.AddField(
            model_name='protecteddocument',
            name='minify',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='protecteddocument',
            name='wrong_passcode_action',
            field=models.CharField(choices=[('prompt', 'Show the prompt again with an error'), ('blank', 'Display a blank page'), ('back', 'Send the visitor back')], default='prompt', max_length=8),
        ),
    ]
