# Generated by Django 5.0.6 on 2026-10-04 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protected_content', '0003_protecteddocument_minify_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='protecteddocument',
            name='block_shortcuts',
            field=models.BooleanField(default=False),
        ),
    ]
