# Generated by Django 5.0.6 on 2026-10-04 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protected_content', '0004_protecteddocument_block_shortcuts'),
    ]

    operations = [
        migrations.AddField(
            model_name='protecteddocument',
            name='original_filename',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
