# Generated by Django 5.0.6 on 2026-10-05 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protected_content', '0005_protecteddocument_original_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='protecteddocument',
            name='allowed_domains',
            field=models.CharField(blank=True, default='', help_text='Comma-separated hostnames the content may run on; blank = anywhere', max_length=500),
        ),
        migrations.AddField(
            model_name='protecteddocument',
            name='block_offline',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='protecteddocument',
            name='break_frames',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='protectedaccesslog',
            name='outcome',
            field=models.CharField(choices=[('granted', 'Granted'), ('denied_passcode', 'Denied — passcode'), ('expired', 'Expired'), ('over_limit', 'Over view limit'), ('denied_referrer', 'Denied — referrer'), ('denied_domain', 'Denied — domain'), ('inactive', 'Inactive')], max_length=20),
        ),
    ]
