# Generated by Django 5.0.6 on 2026-08-26 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailboxes', '0004_mailbox_extra_folders_mailbox_folder_cursors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailbox',
            name='daily_send_limit',
            field=models.PositiveIntegerField(default=0, help_text='Max emails per day from this account. 0 = no limit.'),
        ),
        migrations.AddField(
            model_name='mailbox',
            name='send_day_started',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mailbox',
            name='sent_today',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
